name = "devsheet"
license = "MIT"
licenselink = "https://github.com/fadli0029/devsheet/blob/main/LICENSE"
description = "Minimal monospace Hugo theme for developer portfolios"
homepage = "https://github.com/fadli0029/devsheet"
min_version = "0.112.0"
tags = ["minimal", "portfolio", "blog", "monospace", "dark mode", "light mode"]

[author]
  name = "Fadli Arsani"
  homepage = "https://fadli.sh"
